version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrapy_db
    ports:
      - "5432:5432"

  spider:
    build: ./listings_scraper/
    depends_on:
      - db

  web:
    build: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - db
